SideBarView: Fix sidebar crash
FATAL EXCEPTION: main
Process: com.libremobileos.sidebar, PID: 3567
java.lang.IllegalStateException: State is 'DESTROYED' and cannot be moved to `CREATED` in component com.libremobileos.sidebar.service.SidebarView@57e28d
	at androidx.lifecycle.LifecycleRegistryKt.checkLifecycleStateTransition(LifecycleRegistry.kt:96)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.jvm.kt:126)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.jvm.kt:119)
	at com.libremobileos.sidebar.service.SidebarView.initComposeView(SidebarView.kt:176)
	at com.libremobileos.sidebar.service.SidebarView.showView(SidebarView.kt:86)
	at com.libremobileos.sidebar.service.SidebarService.showSidebar(SidebarService.kt:172)
	at com.libremobileos.sidebar.service.GestureListener.singleFingerSlipAction(GestureListener.kt:35)
	at com.libremobileos.sidebar.service.MGestureManager$SimpleGesture.onFling(MGestureManager.kt:45)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:801)
	at com.libremobileos.sidebar.service.MGestureManager.onTouchEvent(MGestureManager.kt:34)
	at com.libremobileos.sidebar.service.SidebarService$sideLineView$2$1$1.onTouch(SidebarService.kt:51)
	at android.view.View.performOnTouchCallback(View.java:16611)
	at android.view.View.dispatchTouchEvent(View.java:16574)
	at android.view.View.dispatchPointerEvent(View.java:16904)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8123)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7882)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7259)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7316)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7282)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7448)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7290)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7505)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7263)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7316)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7282)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7290)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7263)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10408)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10359)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10327)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10550)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:295)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:387)
	at android.os.Looper.loopOnce(Looper.java:189)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8929)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

Change-Id: I64a04c39f16ee1286d1f29777b38342bd7cfac12
Signed-off-by: rmp22 <195054967+rmp22@users.noreply.github.com>